name: BlockFlow
main: io.github.bananapuncher714.blockflow.BlockFlow
version: 0.1
author: BananaPuncher714
api-version: 1.13
description: Visualize data in 4d with Minecraft
commands:
    blockflow:
        aliases: []